name: release

on:
  push:
    branches:
      - main

jobs:
  release:
    runs-on: ubuntu-latest
    timeout-minutes: 5

    steps:
      - name: Checkout
        uses: actions/checkout@v3.5.3

      - name: Semantic release
        id: semantic-release
        uses: ahmadnassri/action-semantic-release@v2.2.3
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
